# Generated by Django 4.0.1 on 2022-01-16 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_type', models.CharField(choices=[('A', 'TYPE-A'), ('B', 'TYPE-B'), ('C', 'TYPE-C'), ('D', 'TYPE-D')], max_length=2)),
                ('answer_to_question_1', models.IntegerField()),
                ('answer_to_question_2', models.IntegerField()),
                ('answer_to_question_3', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
