# Generated by Django 4.0.1 on 2022-01-16 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanage',
            name='algorithm_type',
            field=models.CharField(blank=True, choices=[('A', 'TYPE-A'), ('B', 'TYPE-B'), ('C', 'TYPE-C'), ('D', 'TYPE-D')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='assetmanage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
