# Generated by Django 4.0.1 on 2022-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage', '0002_alter_assetmanage_algorithm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmanage',
            name='automatic_investment_status',
            field=models.BooleanField(default=False),
        ),
    ]
